### ISSUE TITLE
Discover Devices

### ISSUE THREAD

**Issue by lakmalmpower** [alexa-samples/skill-sample-nodejs-smarthome-switch#12]
Discover Devices not working.
testing not working error massage is

Response:
{
  "errorMessage": "2020-05-16T17:50:44.171Z 47546ffe-6e58-44d2-a9d1-855163d70851 Task timed out after 3.00 seconds"
}

Request ID:
"47546ffe-6e58-44d2-a9d1-855163d70851"

Function Logs:
START RequestId: 47546ffe-6e58-44d2-a9d1-855163d70851 Version: $LATEST
END RequestId: 47546ffe-6e58-44d2-a9d1-855163d70851
REPORT RequestId: 47546ffe-6e58-44d2-a9d1-855163d70851	Duration: 3003.16 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 20 MB	
2020-05-16T17:50:44.171Z 47546ffe-6e58-44d2-a9d1-855163d70851 Task timed out after 3.00 seconds

**Comment by ravirajsawkar** [comment]
Install 'aws-sdk' in working folder
npm install aws-sdk

Upload the code in lambda and try again

**Comment by malcolmcdixon** [comment]
No need to do above as aws-sdk is built into the Lambda execution environment.
Try updating the AlexaResponse.js to the code in another example https://github.com/alexa/skill-sample-nodejs-multi/blob/master/lambda/custom/alexa/skills/smarthome/AlexaResponse.js, please see my post on same issue in another thread https://github.com/alexa/skill-sample-nodejs-smarthome-switch/issues/14#issuecomment-792376815

**Comment by malcolmcdixon** [comment]
No need to do above as aws-sdk is built into the Lambda execution environment.
Try updating the AlexaResponse.js to the code in another example https://github.com/alexa/skill-sample-nodejs-multi/blob/master/lambda/custom/alexa/skills/smarthome/AlexaResponse.js, please see my post on same issue in another thread https://github.com/alexa/skill-sample-nodejs-smarthome-switch/issues/14#issuecomment-792376815

**Comment by malcolmcdixon** [comment]
No need to do above as aws-sdk is built into the Lambda execution environment.
Try updating the AlexaResponse.js to the code in another example https://github.com/alexa/skill-sample-nodejs-multi/blob/master/lambda/custom/alexa/skills/smarthome/AlexaResponse.js, please see my post on same issue in another thread https://github.com/alexa/skill-sample-nodejs-smarthome-switch/issues/14#issuecomment-792376815

**Comment by dievaa** [comment]
The discovery process can potentially fail because of a mismatch between the account's PFM (Preferred market place), the skill locale, and the lambda endpoint region.

Please make sure that these three settings are matching each other.

If you need to check or update the PFM of the account, please follow the steps below:
- Sign into your Amazon retail account 
- Navigate to the "Content and Devices" section of your account: https://www.amazon.com/hz/mycd/myx#/home/settings/payment
- Click "Country/Region Settings" 
- Click "Change" 
- Either choose an existing address from the dropdown menu or enter a new address
- Click "Update"

If after following the steps above you are still running into trouble, please reach out to Alexa Developer Support via the Contact Us page (https://developer.amazon.com/alexa/console/contact-us) and share with us the timestamp of the discovery attempt that failed, the Custmer ID used for testing, the skill ID, and the Discover Response.
