### ISSUE TITLE
Discover Device by Alexa Skill

### ISSUE THREAD

**Issue by ChandanKolambe** [alexa-samples/skill-sample-nodejs-smarthome-switch#14]
I followed each step in instructions and created a lambda function in Virginia region as per given.
I made a test execution on lambda function and it is successful, returning the dummy sample switch(confirmed in logs)
But from Alexa's skill, the account link showed successful as well, but no virtual switch is discovered and no logs in lambda function.

I have an Alexa account, I try to login to https://alexa.amazon.com/ it redirects me to https://alexa.amazon.in/. (I am from India)

What may be the issue? Why Alexa's skill is not triggering my lambda function?

**Comment by schylabs** [comment]
Same issue for me. 
@ChandanKolambe  how did you fix this?

**Comment by Aymkdn** [comment]
Any chance with that guys?

Alexa cannot discover the device… After the 45 seconds of search, it just says "no device found".

**Comment by malcolmcdixon** [comment]
Me too, spent hours going through the convoluted process (to the uninitiated) to find that the last step does not work. The test worked fine but Alexa will not discover the virtual switch if I kissed its arse! Seems like no one can be bothered on the Alexa team to answer why or even update this old sample! Come on guys I want to get into developing smart home devices for personal use, this ain't a great start. Any advice appreciated. Thanks.

UPDATE: After many hours I finally got this to work completely. I don't the exact change that made this work but I changed the region to eu-west-1, which is more local to me. I also used the AlexaResponse.js code from another example which I believe was the main factor https://github.com/alexa/skill-sample-nodejs-multi/blob/master/lambda/custom/alexa/skills/smarthome/AlexaResponse.js.
After device discovery worked the dynamodb update wasn't working either, so I created an IAM user called Developer with AmazonDynamoDBFullAccess permissions. Added an AWS.config.update command with the accessKeyId and secretAccessKey and region as eu-west-1. Also, the sendDeviceState code was changed to:

async function sendDeviceState(endpoint_id, state, value) {
  let dynamodb = new AWS.DynamoDB();

  let params = {
    TableName: "SampleSmartHome",
    Key: { ItemId: { S: endpoint_id } },
    ExpressionAttributeNames: {
      "#S": state,
    },
    ExpressionAttributeValues: {
      ":s": { S: value },
    },
    UpdateExpression: "SET #S = :s",
    ReturnValues: "UPDATED_NEW",
  };

  let request = dynamodb.updateItem(params);

  console.log("index.sendDeviceState request -----");
  console.log(request);

  let response = await request.promise();

  console.log("index.sendDeviceState response -----");
  console.log(response);

  return true;
}

Also, add an await on this line:
   let state_set = await sendDeviceState(

HTH.

**Comment by dievaa** [comment]
The discovery process can potentially fail because of a mismatch between the account's PFM (Preferred market place), the skill locale, and the lambda endpoint region.

Please make sure that these three settings are matching each other.

If you need to check or update the PFM of the account, please follow the steps below:
- Sign into your Amazon retail account 
- Navigate to the "Content and Devices" section of your account: https://www.amazon.com/hz/mycd/myx#/home/settings/payment
- Click "Country/Region Settings" 
- Click "Change" 
- Either choose an existing address from the dropdown menu or enter a new address
- Click "Update"

If after following the steps above you are still running into trouble, please reach out to Alexa Developer Support via the Contact Us page (https://developer.amazon.com/alexa/console/contact-us) and share with us the timestamp of the discovery attempt that failed, the Customer ID used for testing, the skill ID, and the Discover Response.
